const video = (slug, title) => ({provider:'external',url:`https://flairbartending.tv/${slug}/`,title,author:'Chris — FlairBartending.TV',language:'en',checkedAt:'2026-09-03'});
// Original, deliberately short practice briefs. Videos are external references,
// not copied course content; progression and criteria belong to Constante.
export const SKILLS = [
  {id:'basics',name:'Prises et contrôle',level:1,category:'Fondamentaux',requires:[],description:'Prendre, passer et reposer une bouteille d’entraînement avec confiance.',steps:['Dégage un espace, utilise une bouteille de flair incassable et un tin vide.','Prends et repose la bouteille lentement, puis passe-la entre tes mains sans la lancer.','Réalise dix passages et poses contrôlés. Laisse tomber un objet qui t’échappe plutôt que de le poursuivre.'],tips:'Garde une prise détendue et travaille à faible hauteur.',errors:'Serrer trop fort, accélérer ou s’entraîner près de verres.',criterion:'Un passage de main et une pose stables, sans rattrapage précipité.',resources:[video('flair-lesson-1-the-drop','The Drop — débuter et pratiquer')],reps:10},
  {id:'tin-spin',name:'Tin Spin',level:1,category:'Working flair',requires:['basics'],description:'Faire tourner le tin en gardant un geste compact.',steps:['Observe le tutoriel et reproduis la prise à l’arrêt.','Cherche une demi-rotation régulière avant un tour complet.','Reviens à une réception stable à chaque essai.'],tips:'Travaille chaque main séparément, sans chercher la vitesse.',errors:'Donner une grande impulsion avec l’épaule ou perdre l’axe.',criterion:'Un tour régulier, réception maîtrisée, sans chute.',resources:[video('flair-lesson-20-tin-spin','Tin Spin — démonstration')],reps:10},
  {id:'cradle',name:'Back of the Hand Cradle',level:1,category:'Working flair',requires:['basics'],description:'Accueillir une bouteille sur le dos des mains puis la reprendre.',steps:['Observe la position des mains dans la vidéo.','Place d’abord la bouteille sur les deux mains sans lancer.','Ajoute un trajet très court, puis une reprise contrôlée.'],tips:'Apprends avec une bouteille incassable. Garde le mouvement proche du corps.',errors:'Lancer trop haut ou écarter excessivement les mains.',criterion:'Accueil et reprise propres, sans choc ni chute.',resources:[video('flair-lesson-2-back-of-the-hand-cradle','Back of the Hand Cradle')],reps:10},
  {id:'grip-pour',name:'Change Grip → Pour',level:1,category:'Working flair',requires:['basics'],description:'Changer de prise pour terminer naturellement en position de versement.',steps:['Prépare ton tin avant de démarrer.','Décompose les changements de prise à vide, en suivant le tutoriel.','Rassemble le geste lentement et termine au-dessus du tin.'],tips:'La fin du mouvement doit servir le versement.',errors:'Forcer le poignet ou commencer sans récipient prêt.',criterion:'Changement de prise fluide et arrêt précis en position de versement.',resources:[video('flair-lesson-3-change-grip-circle-into-pour','Change Grip Circle Into Pour')],reps:10},
  {id:'tin-roll',name:'Tin Roll sur l’avant-bras',level:2,category:'Working flair',requires:['tin-spin'],description:'Faire rouler le tin sur une courte portion du bras.',steps:['Trouve une rotation stable avant de chercher le roulement.','Commence par un trajet jusqu’à l’avant-bras.','Augmente l’amplitude seulement quand la réception reste facile.'],tips:'Reste sur un petit trajet tant que le tin oscille.',errors:'Chercher tout le bras immédiatement ou laisser le tin partir derrière soi.',criterion:'Roulement court régulier et réception contrôlée.',resources:[video('flair-lesson-21-tin-roll-down-arm','Tin Roll Down Arm')],reps:10},
  {id:'stall',name:'Hand Stall — équilibre',level:2,category:'Fondamentaux',requires:['cradle'],description:'Stabiliser une bouteille d’entraînement sur le dos de la main.',steps:['Place la bouteille avec l’autre main, sans lancer.','Trouve une position d’équilibre confortable.','Tiens trois secondes puis reprends la bouteille proprement.'],tips:'Reste près d’un tapis, à faible hauteur.',errors:'Commencer par un lancer ou crisper la main.',criterion:'Équilibre de trois secondes et reprise sans chute.',resources:[video('flair-lesson-16-the-stall','The Stall — position et équilibre')],reps:10},
  {id:'service-combo',name:'Combo de service',level:2,category:'Combos',requires:['tin-spin','grip-pour'],description:'Enchaîner un geste au tin et une mise en position de versement.',steps:['Pose la bouteille ; réalise un Tin Spin, puis repose le tin.','Prends la bouteille et réalise Change Grip → Pour au-dessus du tin.','Répète la séquence sans précipiter la transition.'],tips:'Routine Constante : les deux vidéos montrent les gestes séparément.',errors:'Vouloir tout lancer en même temps ou oublier la pose intermédiaire.',criterion:'Séquence entière maîtrisée, récipient prêt et aucun objet échappé.',resources:[video('flair-lesson-20-tin-spin','Geste 1 — Tin Spin'),video('flair-lesson-3-change-grip-circle-into-pour','Geste 2 — Change Grip → Pour')],reps:10},
  {id:'contact-combo',name:'Combo de contrôle',level:3,category:'Combos',requires:['cradle','stall','tin-roll'],description:'Assembler les acquis en une courte routine de pratique.',steps:['Réalise le Cradle puis repose la bouteille.','Place-la en Hand Stall, tiens trois secondes et repose-la.','Termine avec ton roulement court de tin.'],tips:'Les poses entre les gestes font partie de cette routine Constante.',errors:'Supprimer les pauses de contrôle trop tôt.',criterion:'Trois gestes stables enchaînés avec leurs poses, sans chute.',resources:[video('flair-lesson-2-back-of-the-hand-cradle','Cradle'),video('flair-lesson-16-the-stall','Stall'),video('flair-lesson-21-tin-roll-down-arm','Tin Roll')],reps:10}
];
export const skillById = id => SKILLS.find(s=>s.id===id);
