import {esc,uid,clone,readingDays,historyList,bind} from '../../core/ui.js';
import {initialReading,validateReading,finishReading,elapsedSeconds} from './model.js';
export const ReadingModule={id:'reading',name:'Lecture',version:1,initial:initialReading,validate:validateReading,mount:mountReading};
function mountReading({root,read,save}) {
  let timer;
  const update=data=>{save(validateReading(data));render();};
  function render() {
    clearInterval(timer);const data=read();
    if(data.draft){renderSession(data);return;}
    root.innerHTML=`<div class="ey">UN PEU, SOUVENT</div><h1>Lecture</h1><div class="card"><div class="row"><span class="pill">${readingDays(data.sessions)} jours lus / 7</span><span class="pill">Objectif ${data.target} jours</span></div><div class="hero">${data.minutes} min</div><p class="muted">Pour aujourd’hui. Une page suffit quand la journée est chargée.</p><label for="reading-book">Livre en cours</label><select id="reading-book"><option value="">Sans livre renseigné</option>${data.books.filter(b=>!b.finishedAt).map(b=>`<option value="${esc(b.id)}" ${b.id===data.bookId?'selected':''}>${esc(b.title)}</option>`).join('')}</select><div class="two-buttons"><button class="primary" data-start="normal">Lire ${data.minutes} minutes</button><button class="secondary" data-start="minimum">1 page suffit</button></div></div><details class="card"><summary>Mes livres et mon rythme</summary><form id="reading-add"><label>Nouveau livre<input name="title" maxlength="160" required placeholder="Titre du livre"></label><button class="secondary">Ajouter le livre</button></form>${data.books.map(b=>`<div class="ex"><span>${esc(b.title)}${b.finishedAt?' · terminé':''}</span>${!b.finishedAt?`<button class="chip" data-finish-book="${esc(b.id)}">Terminé</button>`:''}</div>`).join('')}<label>Jours de lecture souhaités par semaine<select id="reading-target">${[1,2,3,4,5,6,7].map(n=>`<option ${n===data.target?'selected':''}>${n}</option>`).join('')}</select></label><p class="muted">Pas de rattrapage, pas de série à sauver. Ton rythme peut évoluer.</p></details><div class="card"><div class="grid"><div class="stat"><b>${data.sessions.length}</b>séances</div><div class="stat"><b>${data.sessions.reduce((n,s)=>n+s.pages,0)}</b>pages renseignées</div></div></div><details class="card"><summary>Historique de lecture</summary>${historyList(data.sessions,s=>`${s.bookTitle||'Lecture'} · ${s.mode==='minimum'?'minimum':Math.round(s.seconds/60)+' min'}${s.pages?' · '+s.pages+' pages':''}`)}</details>`;
    root.querySelector('#reading-book').onchange=e=>{const next=clone(read());next.bookId=e.target.value||null;update(next);};
    root.querySelector('#reading-target').onchange=e=>{const next=clone(read());next.target=Number(e.target.value);update(next);};
    root.querySelector('#reading-add').onsubmit=e=>{e.preventDefault();const title=new FormData(e.target).get('title').trim();if(!title)return;const next=clone(read()),id=uid();next.books.push({id,title,createdAt:new Date().toISOString()});next.bookId=id;update(next);};
    bind(root,'[data-finish-book]',el=>{const next=clone(read());next.books.find(b=>b.id===el.dataset.finishBook).finishedAt=new Date().toISOString();if(next.bookId===el.dataset.finishBook)next.bookId=null;update(next);});
    bind(root,'[data-start]',el=>{const next=clone(read());next.draft={id:uid(),mode:el.dataset.start,bookId:next.bookId,bookTitle:next.books.find(b=>b.id===next.bookId)?.title||'',goalMinutes:next.minutes,elapsed:0,runningSince:el.dataset.start==='normal'?Date.now():null};update(next);});
  }
  function renderSession(data) {
    const d=data.draft,minimum=d.mode==='minimum';
    root.innerHTML=`<div class="ey">LECTURE EN COURS</div><h1>${minimum?'Une page suffit.':'Un moment pour lire.'}</h1><p>${esc(d.bookTitle||'Ton livre t’attend.')}</p><div class="card work"><div class="big" id="reading-clock">${minimum?'1 page':'00:00'}</div><div class="muted">${minimum?'Le minimum compte.':`Objectif : ${d.goalMinutes} minutes · tu peux continuer au-delà.`}</div>${!minimum?`<button class="secondary" id="reading-pause">${d.runningSince?'Pause':'Reprendre'}</button>`:''}</div><form id="reading-done" class="card"><label>Pages lues ${minimum?'':'(facultatif)'}<input name="pages" type="number" min="${minimum?1:0}" max="10000" step="1" value="${minimum?1:0}" required></label><label>Comment c’était ?<select name="feedback"><option value="0">Bien</option><option value="1">Facile, je pourrais lire un peu plus</option><option value="-1">Difficile à caser aujourd’hui</option></select></label><button class="primary">J’ai lu — enregistrer</button></form><button class="secondary" id="reading-cancel">Annuler cette séance</button>`;
    const tick=()=>{const clock=root.querySelector('#reading-clock');if(!clock || minimum)return;const seconds=elapsedSeconds(read().draft);clock.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;};tick();timer=setInterval(tick,1000);
    if(!minimum)root.querySelector('#reading-pause').onclick=()=>{const next=clone(read());if(next.draft.runningSince){next.draft.elapsed+=Math.max(0,Date.now()-next.draft.runningSince);next.draft.runningSince=null;}else next.draft.runningSince=Date.now();update(next);};
    root.querySelector('#reading-done').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target);try{update(finishReading(read(),{pages:Number(form.get('pages')),seconds:minimum?0:elapsedSeconds(read().draft),feedback:Number(form.get('feedback')),date:new Date().toISOString()}));}catch(error){alert(error.message);}};
    root.querySelector('#reading-cancel').onclick=()=>{if(confirm('Annuler la séance en cours sans l’ajouter à l’historique ?')){const next=clone(read());next.draft=null;update(next);}};
  }
  render();return {refresh:render,hasSession:()=>!!read().draft};
}
